#!/bin/bash


INTERVAL=5
NUMBER=12
COMMAND="date"

echo Please Enter Interval:
read interval
INT=$interval

echo Please Enter Retry count:
read retry
RCNT=$retry

echo Please Enter Command:
read cmd
CMD=$cmd


EXEC=`$CMD`
RES=$?
case $RES in 
0)
 EXEC=`$CMD`
  echo "$EXEC"
  echo Done!
  
  if [[ $? -ne "" ]] ; then
   EXEC=`$COMMAND`
   echo you dont enter command
   else 
   echo hamed
  fi
;;
127)
 for A in $(seq 1 $RCNT) ; do
   A=`$CMD`
    echo "$A"
   sleep "$INT"
 done
 ;;
*)
esac





